import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  tutorial: [
    'intro',
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'}
  ],
  tuccarnaseq: [
    'tucca-rna-seq/introduction',
    {
      type: 'category',
      label: 'Background Learning',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'tucca-rna-seq/background-learning/learn-rna-seq',
        'tucca-rna-seq/background-learning/learn-unix',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'tucca-rna-seq/getting-started/installation/new-user-install',
        'tucca-rna-seq/getting-started/installation/fresh-project-install',
        {
          type: 'category',
          label: 'The `config` directory',
          link: {
            type: 'generated-index',
            description: 'How to configure the tucca-rna-seq pipeline for your experiment'
          },
          items: [
            'tucca-rna-seq/getting-started/config-setup/config-yaml',
            'tucca-rna-seq/getting-started/config-setup/multiqc-config-yaml',
            'tucca-rna-seq/getting-started/config-setup/samples-and-units'
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Running the Workflow',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'tucca-rna-seq/running-the-workflow/salmon-counts',
      ],
    },
    {
      type: 'category',
      label: 'Helpful Resources',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'tucca-rna-seq/helpful-resources/tufts-hpc-in-vscode',
        'tucca-rna-seq/helpful-resources/useful-r-extensions',
      ],
    },
    {
      type: 'category',
      label: 'Reproducibility',
      link: {
        type: 'generated-index',
      },
      collapsed: true,
      items: [
        'tucca-rna-seq/reproducibility/git',
        'tucca-rna-seq/reproducibility/renv',
        'tucca-rna-seq/reproducibility/snakemake',
      ],
    },
    'tucca-rna-seq/citing-the-workflow',
    'tucca-rna-seq/help',
  ],
};

export default sidebars;
