import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /* tutorial: [
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'}
  ], */
  tucca_rna_seq: [
    'tucca-rna-seq/introduction',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'tucca-rna-seq/getting-started/deployment',
        'tucca-rna-seq/getting-started/installation',
        'tucca-rna-seq/getting-started/configuration',
        'tucca-rna-seq/getting-started/running',
      ],
    },
    {
      type: 'category',
      label: 'Deployment via Tufts HPC',
      collapsed: true,
      items: [
        'tucca-rna-seq/getting-started-tufts/installation',
        'tucca-rna-seq/getting-started-tufts/configuration',
        'tucca-rna-seq/getting-started-tufts/running',
      ],
    },
    'tucca-rna-seq/citing-the-workflow',
    'tucca-rna-seq/help',
  ],
  helpful_resources: [
    'helpful-resources/reproducibility',
    'helpful-resources/tufts-hpc-in-vscode',
    'helpful-resources/r-extensions',
  ]
};

export default sidebars;
