import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /* tutorial: [
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'}
  ], */
  tucca_rna_seq: [
    'tucca-rna-seq/introduction',
    {
      type: 'link',
      label: 'GitHub Repository',
      href: 'https://github.com/tucca-cellag/tucca-rna-seq',
    },
    {
      type: 'category',
      label: 'Data Collection 101 for RNA-Seq',
      collapsed: true,
      items: [
        'tucca-rna-seq/data-collection/data-collection-why',
        'tucca-rna-seq/data-collection/data-collection-how',
      ],
    },
    {
      type: 'category',
      label: 'Installation and Configuration of tucca-rna-seq',
      collapsed: true,
      items: [
        'tucca-rna-seq/install-and-config/snakemake-primer',
        'tucca-rna-seq/install-and-config/deployment',
        'tucca-rna-seq/install-and-config/installation',
        'tucca-rna-seq/install-and-config/configuration',
      ],
    },
    'tucca-rna-seq/running',
    'tucca-rna-seq/enrichment-analysis',
    {
      type: 'category',
      label: 'For Tufts Users',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'tucca-rna-seq/tufts-specific/hpc-quick-start',
      },
      items: [
        'tucca-rna-seq/tufts-specific/hpc-quick-start',
        'tucca-rna-seq/tufts-specific/hpc-best-practices',
        'tucca-rna-seq/tufts-specific/tufts-hpc-in-vscode',
      ],
    },
    'tucca-rna-seq/citing-the-workflow',
    'tucca-rna-seq/help',
  ],
  helpful_resources: [
    'helpful-resources/learn-about-cell-ag',
    'helpful-resources/reproducibility',
    'helpful-resources/r-extensions',
  ],
  publications: [
    {
      type: 'category',
      label: 'Our Publications',
      collapsed: false,
      items: [
        'publications/ast1',
      ],
    },
    
  ]
};

export default sidebars;
